### PR TITLE
Public error properties

### PR DESCRIPTION
**Pull request by marijnschilling**
I had to make some properties of the `TeapotError` public so to be able to convert a `TeapotError` to a `ToshiError`. 

The initialiser i needed to make public to be able to test the init with teapot error method of the `ToshiError`

### CODE REVIEW

**Comment by elland** [comment]
Interesting. Looks good so far, but I'd love some example code of how it's being used? Then we can add it to the Readme as well 💪🏽.

**Comment by marijnschilling** [comment]
Should we add that too readme? Its more something for the readme of toshi :) I just made the properties public for now.

**Comment by elland** [comment]
I think so, seems like an interesting use case of "things you can do with teapot". 👍

**Comment by marijnschilling** [comment]
ow hmmm maybe 🤔  But i still need to fully implement it in Toshi. Will do that first! Maybe will work on this PR if necessary Will set it to [WIP]

**Comment by elland** [comment]
I think we can close this, and merge the other one where tests are passing?

**Pull request closed without merging**
