### PR TITLE
Cleaned up code formatting.

### PR DESCRIPTION
**Pull request by elland**

### CODE REVIEW

**Review by designatednerd — COMMENTED** [review]
Looks good - you wanna add SwiftLint to enforce this stuff going forward?

**Comment by elland** [comment]
I guess it's fine if it's there, but not really looking forward to setting it up. 😅 Last time I looked into it it was very annoying.

**Comment by designatednerd** [comment]
IIRC it's not that bad if you've got the config from the code standards repo, but we can merge this without it and do that as a separate PR

**Review by designatednerd — APPROVED** [review]
:shipit:

**Pull request merged**
