### PR TITLE
Add multipart upload.

### PR DESCRIPTION
**Pull request by elland**

### CODE REVIEW

**Comment by elland** [comment]
I think `RequestParameter` could have a better name. 🤔

**Comment by 3lvis** [comment]
You can always just use https://github.com/3lvis/networking instead.

**Comment by elland** [comment]
Not sure how having cyclical arguments fits in with a code review. 🤔

**Comment by 3lvis** [comment]
It already has this feature (and more) and it's unit tested and used in several other apps, not cynical at all.

**Comment by elland** [comment]
_cyclical_ .

**Comment by 3lvis** [comment]
Duh, my bad 😅

**Comment by 3lvis** [comment]
I thought the final conclusion was that instead of following the same path that Networking already gives us, we would use this library to wrap up Alamofire, maybe I misunderstood.

I don't see the point on basically rebuilding Networking just with minor changes.

**Comment by elland** [comment]
That might be our future plan for it, but for now I need to get our current project out. 🤔

**Comment by 3lvis** [comment]
Might be the wrong approach to do that by rebuilding what Networking already gave us.

**Comment by elland** [comment]
If there are no code-review comments, I'll just merge it then.

**Pull request merged**
